name: CypressAndCucumber

on:
  workflow_dispatch
  
jobs:
     Run_test:
        runs-on: windows-latest
        strategy:
            matrix:
             node-version: [14.17.0]
             
        steps:
         - uses: actions/checkout@v2.5.0
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/checkout@v2.5.0
           with:
            node-version: ${{ matrix.node-version }}
         - name: update node manager
           run: npm i npm@latest
         - name: install all dependencies
           run: npm i
         - name: install webdriver
           run: npm init wdio
         - name: install Allure
           run: npm install @wdio/allure-reporter
         - name: Install selenium standalone
           run: npm install @wdio/selenium-standalone-service
         - name: run test
           continue-on-error: true
           run: npm run wdio
         - name: Create Report
           if: always()
           run: npm run allureRefresh
         - name: Upload artifact allure-report
           uses: actions/upload-artifact@v1
           if: always()
           with:
             name: allure-report
             path: ./allure-report
         - name: Deploy to pages
           if: always()
           uses: peaceiris/actions-gh-pages@v3.7.3
           with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_branch: gh-pages
              publish_dir: allure-report/
             
 
