name: CypressAndCucumber

on:
  workflow_dispatch
  
jobs:
     Run_test:
        runs-on: windows-latest
        strategy:
            matrix:
             node-version: [14.17.0]
             
        steps:
         - name: Code Checkout
           uses: actions/checkout@v2.5.0
         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/checkout@v2.5.0
           with:
            node-version: ${{ matrix.node-version }}
         - name: update node manager
           run: npm i npm@latest
         - name: install all dependencies
           run: npm install
         - name: Run docker-compose
           run: docker-compose -f ./selenium-4-grid.yml up
         - name: run test
           continue-on-error: true
           run: npm run wdio
         - name: Create Report
           if: always()
           run: npm run allureRefresh
         - name: Upload artifact allure-report
           uses: actions/upload-artifact@v2
           if: always()
           with:
             name: allure-report
             path: allure-report/
         - name: Get Allure history
           uses: actions/checkout@v2
           if: always()
           continue-on-error: true
           with:
                ref: gh-pages
                path: gh-pages
         - name: Deploy report to Github Pages
           if: always()
           uses: peaceiris/actions-gh-pages@v2
           env:
                PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                PUBLISH_BRANCH: gh-pages
                PUBLISH_DIR: allure-history
             
 
